
---
# CCP4 specific configurations for the cluster based on SL7
# to be run with this command:
# elasticluster setup ccp4cluster -- --tags "ccp4" /path/to/ccp4_setup_sl7.yml
# groups of nodes as found in the inventory :
#   slurm_master
#   slurm_worker


- name: ccp4-ed specific configuration on both master and worker nodes
  tags:
        - after
        - ccp4
  hosts: slurm_master, slurm_worker

  vars:
      - local_user: 'lii26466'
      - remote_user: 'lii26466'


  tasks:
           - name: install dependencies
             apt:
                    name:
                     - libopenmpi-dev
                     - libblas-dev
                     - liblapack-dev
                    state: latest

           - name: create ccp4 user group
             group:
                    name: ccp4
                    state: present
                    gid: 13749


           - name: add user to sudoers
             lineinfile:
                    path: /etc/sudoers.d/cloud
                    line: ' {{ remote_user }}  ALL=(ALL)       NOPASSWD: ALL'
                    state: present

################################################################
################################################################
#### MASTER ONLY
################################################################
################################################################
- name: configuration on the head node only
  tags:
        - after
        - ccp4
        - master
  hosts: slurm_master
  become: true

  vars:
      - local_user: 'lii26466'
      - remote_user: 'lii26466'

  tasks:
           - name: copy the .bashrc file
             copy:
                    src: '/home/{{ local_user }}/.bashrc'
                    dest: '/home/{{ remote_user }}/.bashrc'
                    owner: '{{ remote_user }}'
                    group: ccp4
                    mode: '0644'

           - name: copy the .bash_aliases file
             copy:
                    src: '/home/{{ local_user }}/.bash_aliases'
                    dest: '/home/{{ remote_user }}/.bash_aliases'
                    owner: '{{ remote_user }}'
                    group: ccp4
                    mode: '0644'

#           - name: copy the binaries
#             copy:
#                    src: /home/lii26466_local/bin/felix
#                    dest: /home/lii26466/bin/felix
#                    owner: lii26466
#                    group: ccp4
#                    mode: '0644'

################################################################
################################################################
#### NODES
################################################################
################################################################
- name: configuration on the compute node only
  tags:
    - after
    - ccp4
    - worker
  hosts: slurm_worker


  tasks:
    - name: latest version of all required packages installed
      yum:
        name:
          - libblas-dev
          - liblapack-dev
        state: latest
