
---
# CCP4 specific configurations for the cluster based on SL7
# to be run with this command:
# elasticluster setup ccp4cluster -- --tags "ccp4" /path/to/ccp4_setup_sl7.yml
# groups of nodes as found in the inventory :
#   slurm_master
#   slurm_worker


- name: ccp4-ed specific configuration on both master and worker nodes
  tags:
        - after
        - ccp4
  hosts: slurm_master, slurm_worker

  vars:
      - user: 'lii26466'

  tasks:
           - name: install dependencies
             apt:
                    name:
                     - libopenmpi-dev
                     - libblas-dev
                     - liblapack-dev
                    state: latest

           - name: create ccp4 user group
             group:
                    name: ccp4
                    state: present
                    gid: 13749


           - name: add user to sudoers
             lineinfile:
                    path: /etc/sudoers.d/cloud
                    line: ' {{ user }}  ALL=(ALL)       NOPASSWD: ALL'
                    state: present

           - name: copy the script
             copy:
                     src: /home/{{ user }}/ccp4ED_cluster/scripts/fftw_installer.sh
                     dest: /home/{{ user }}/fftw_installer.sh
                     owner: '{{ user }}'
                     group: ccp4
                     mode: '0755'

           - name: Execute the script
             command: bash fftw_installer.sh

################################################################
################################################################
#### MASTER ONLY
################################################################
################################################################
- name: configuration on the head node only
  tags:
        - after
        - ccp4
        - master
  hosts: slurm_master
  become: true

  vars:
      - user: 'lii26466'

  tasks:
           - name: copy the .bashrc file
             copy:
                    src: /home/{{ user }}/.bashrc
                    dest: /home/{{ user }}/.bashrc
                    owner: '{{ user }}'
                    group: ccp4
                    mode: '0644'

           - name: copy the .bash_aliases file
             copy:
                    src: /home/{{ user }}/.bash_aliases
                    dest: /home/{{ user }}/.bash_aliases
                    owner: '{{ user }}'
                    group: ccp4
                    mode: '0644'

           - name: copy the script
             copy:
                     src: /home/{{ user }}/ccp4ED_cluster/scripts/felix_installer.sh
                     dest: /home/{{ user }}/felix_installer.sh
                     owner: '{{ user }}'
                     group: ccp4
                     mode: '0755'

           - name: Execute the script
             command: bash felix_installer.sh

           - name: copy the run_felix.sh script
             copy:
                   src: /home/{{ user }}/ccp4ED_cluster/scripts/run_felix.sh
                   dest: /home/{{ user }}/run_felix.sh
                   owner: '{{ user }}'
                   group: ccp4
                   mode: '0755'
